### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by digitalGangstar** [digitalGangstar/TODO-List#1]
---
 - [ ] **Apenas o Prompt de Comando**
   - [ ] Criar Menu
     - [ ] Mostrar Tarefas
     - [ ] Criar Tarefa
     - [ ] Destruir Tarefa
     - [ ] Ler arquivo
     - [ ] Salvar Arquivo
 - [ ] Correcao de Erros e Bugs

---
 - [ ] **Inteface Grafica**
   - [ ] Configurar Interface Principal
   - [ ] Configurar Eventos do Programa
   - [ ] Configurar Notificacoes
